# Tuning para ~256GB RAM / workload OLTP+analytics leve (ajuste ao node)
listen_addresses = '*'
max_connections = 300
shared_buffers = 64GB
effective_cache_size = 192GB
work_mem = 256MB
maintenance_work_mem = 2GB
wal_level = logical
max_wal_senders = 10
synchronous_commit = on
log_min_duration_statement = 500
log_statement = 'ddl'
timezone = 'America/Sao_Paulo'
