CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS detection;
CREATE SCHEMA IF NOT EXISTS policy;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS dlp;
CREATE SCHEMA IF NOT EXISTS admin;
